#!/usr/bin/env php
<?php

declare(strict_types=1);

use Symfony\Component\Console\Application;

$container = require __DIR__ . '/config/bootstrap.php';

/** @var Application $application */
$application = $container->get(Application::class);
$application->run();
